### ISSUE TITLE
incongruenza dati italiani tra box iniziale e riepilogo per nazione

### ISSUE THREAD

**Issue by carminepat** [giacomoalonzi/covidlive.it#89]
Nel "carousel" con i 3 box iniziali, dove vengono riportati i dati complessivi italiani, vengono riportati dei numeri che poi non corrispondono nel riepilogo delle nazioni (parte successiva al dettaglio regionale)

**Comment by giacomoalonzi** [comment]
Ciao @carminepat, si la parte incorretta è proprio quella delle nazioni. I dati provengono da altra fonte, sto cercando di capire insieme a chi mi fornisce quei dati il motivo.

**Comment by carminepat** [comment]
Avevo già immaginato, che il problema fosse la fonte dei dati. Buon lavoro
